### ISSUE TITLE
LVIS training 

### ISSUE THREAD

**Issue by jihwanp** [fcjian/RPL#1]
Hi I have a question about your implementation.
There seems no preparation for cropped images from LVIS base classes and related dataset loader.
Is there any plan to release the related code or config?

Thanks for providing great work!

**Comment by fcjian** [comment]
Yes, the config is [run_train_lvis.sh](https://github.com/fcjian/RPL/blob/master/scripts/run_train_lvis.sh), and we will release the code for data preparation and detailed training steps soon.

**Comment by fcjian** [comment]
@jihwanp We have now updated the code for data preparation and detailed training steps, please see 'README.md'.
